[package]
name = "voxi-core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
rust_decimal = {version = "1.25", features = ["serde"]}
uuid = {version = "1.1", features = ["v4", "serde"]}
serde = {version = "1.0.151", features = ["derive", "rc"]}
serde_json = "1.0.91"
thiserror = "1.0"

# voxi sql dependencies
error-stack = { version = "0.2.4", features = ["spantrace", "anyhow"], optional = true}
error-stack-derive = { git = "https://github.com/vaniusrb/error-stack-derive.git", optional = true }
log = { version = "0.4", optional = true }
dyn-clonable = { version = "0.9", optional = true }

[dev-dependencies]
rust_decimal_macros = "1.25"
pretty_assertions = "1.3"

[features]
sql = ["dep:error-stack", "dep:error-stack-derive", "dep:log", "dep:dyn-clonable"]
objects = ["dep:log"]
default = ["sql", "objects"]
